// <auto-generated />
using System;
using EmployeeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726021522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeManagement.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OfficePhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Address = "123 Le Loi St",
                            DepartmentName = "Sales",
                            OfficePhone = "0123456789"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Address = "456 Hai Ba Trung St",
                            DepartmentName = "Marketing",
                            OfficePhone = "0234567891"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Address = "789 Ha Noi Rd",
                            DepartmentName = "IT",
                            OfficePhone = "0345678912"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Address = "321 Cach Mang Thang 8",
                            DepartmentName = "HR",
                            OfficePhone = "0456789123"
                        },
                        new
                        {
                            DepartmentId = 5,
                            Address = "280 An Duong Vuong",
                            DepartmentName = "Sales",
                            OfficePhone = "0456789123"
                        },
                        new
                        {
                            DepartmentId = 6,
                            Address = "273 Nguyen Trai",
                            DepartmentName = "R&D",
                            OfficePhone = "0456789123"
                        },
                        new
                        {
                            DepartmentId = 7,
                            Address = "321 Cach Mang Thang 8",
                            DepartmentName = "Customer Service",
                            OfficePhone = "0456789123"
                        },
                        new
                        {
                            DepartmentId = 8,
                            Address = "987 Truong Dinh",
                            DepartmentName = "Finance",
                            OfficePhone = "0567891234"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhotoImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1979, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "alice@example.com",
                            EmployeeName = "Alice Johnson",
                            Gender = false,
                            Phone = "012345678",
                            PhotoImagePath = "/images/photos/alice.jpg",
                            Salary = 1900m
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1997, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "bob@example.com",
                            EmployeeName = "Bob Smith",
                            Gender = true,
                            Phone = "023456789",
                            PhotoImagePath = "/images/photos/bob.jpg",
                            Salary = 1100m
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(1993, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "carol@example.com",
                            EmployeeName = "Carol Lee",
                            Gender = false,
                            Phone = "034567891",
                            PhotoImagePath = "/images/photos/carol.jpg",
                            Salary = 1300m
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(1995, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "david@example.com",
                            EmployeeName = "David Kim",
                            Gender = true,
                            Phone = "045678912",
                            PhotoImagePath = "/images/photos/david.jpg",
                            Salary = 1500m
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateOfBirth = new DateTime(1999, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "eva@example.com",
                            EmployeeName = "Eva Brown",
                            Gender = false,
                            Phone = "056789123",
                            PhotoImagePath = "/images/photos/eva.jpg",
                            Salary = 1700m
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.HasOne("EmployeeManagement.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeManagement.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
